Repository smileidentity/flutter, pull requests merged in 2025-01, with the labels that each got.

#133 Fix/screens on document capture
  CHANGELOG.md
  android/build.gradle
  android/src/main/kotlin/com/smileidentity/flutter/SmileIDDocumentCaptureView.kt
  example/pubspec.lock
  pubspec.yaml
Labels: Review effort [1-5]: 4

#134 Skip Metadata Version Check
  CHANGELOG.md
  android/build.gradle
  example/android/app/build.gradle
Labels: Review effort [1-5]: 1

#140 Add Missing Extras on iOS Mapper
  CHANGELOG.md
  example/lib/main.dart
  ios/Classes/Mapper.swift
  pubspec.yaml
Labels: Review effort [1-5]: 2
