Repository smileidentity/flutter, pull requests merged in 2025-06, with the labels that each got.

#170 fix document capture and selfie capture screen crash
  CHANGELOG.md
  android/build.gradle
  android/src/main/kotlin/com/smileidentity/flutter/SmileIDDocumentCaptureView.kt
  android/src/main/kotlin/com/smileidentity/flutter/SmileIDPlugin.kt
  android/src/main/kotlin/com/smileidentity/flutter/SmileIDSmartSelfieCaptureView.kt
  example/android/build.gradle
  example/ios/Podfile.lock
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/SmileIDPlugin.swift
  pubspec.yaml
Labels: Review effort 2/5

#176 Release v11.0.2 🤙🏽
  .github/workflows/release_android.yml
  CHANGELOG.md
  android/gradle/libs.versions.toml
  pubspec.yaml
Labels: Review effort 1/5

#178 Fix dark mode issues
  CHANGELOG.md
  ios/Classes/SmileIDDocumentCaptureView.swift
  ios/Classes/SmileIDSmartSelfieCaptureView.swift
  sample/ios/Podfile.lock
  sample/pubspec.lock
Labels: Review effort 3/5

#179 Update Dependabot Setup
  .github/dependabot.yaml
  .github/dependabot.yml
Labels: Review effort 2/5

#180 Re Org android sdk 🧱
  .github/workflows/build.yaml
  android/src/main/kotlin/com/smileidentity/flutter/SmileIDPlugin.kt
  android/src/main/kotlin/com/smileidentity/flutter/mapper/Mapper.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/biometric/SmileIDBiometricKYC.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/capture/SmileIDDocumentCaptureView.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/capture/SmileIDSmartSelfieCaptureView.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/document/SmileIDDocumentVerification.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/enhanceddocv/SmileIDEnhancedDocumentVerification.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/enhancedselfie/SmileIDSmartSelfieAuthenticationEnhanced.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/enhancedselfie/SmileIDSmartSelfieEnrollmentEnhanced.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/selfie/SmileIDSmartSelfieAuthentication.kt
  android/src/main/kotlin/com/smileidentity/flutter/products/selfie/SmileIDSmartSelfieEnrollment.kt
  android/src/main/kotlin/com/smileidentity/flutter/results/SmartSelfieCaptureResult.kt
  android/src/main/kotlin/com/smileidentity/flutter/utils/SmileIDUtils.kt
  android/src/main/kotlin/com/smileidentity/flutter/views/SmileComposablePlatformView.kt
  android/src/main/kotlin/com/smileidentity/flutter/views/SmileSelfieComposablePlatformView.kt
  lib/products/biometric/smile_id_biometric_kyc.dart
  lib/products/capture/smile_id_document_capture_view.dart
  lib/products/capture/smile_id_smart_selfie_capture_view.dart
  lib/products/document/smile_id_document_verification.dart
  lib/products/enhanceddocv/smile_id_enhanced_document_verification.dart
  lib/products/enhancedselfie/smile_id_smart_selfie_authentication_enhanced.dart
  lib/products/enhancedselfie/smile_id_smart_selfie_enrollment_enhanced.dart
  lib/products/selfie/smile_id_smart_selfie_authentication.dart
  lib/products/selfie/smile_id_smart_selfie_enrollment.dart
  lib/smile_id.dart
  lib/smile_id_biometric_kyc.dart
  lib/smile_id_document_capture_view.dart
  lib/smile_id_document_verification.dart
  lib/smile_id_service.dart
  lib/smile_id_smart_selfie_authentication.dart
  lib/smile_id_smart_selfie_authentication_enhanced.dart
  lib/smile_id_smart_selfie_capture_view.dart
  lib/smile_id_smart_selfie_enrollment.dart
  lib/smile_id_smart_selfie_enrollment_enhanced.dart
  lib/smileid_messages.g.dart
  lib/views/smile_view.dart
  lint.sh
  pigeon/messages.dart
  sample/android/build.gradle.kts
  sample/android/settings.gradle.kts
  sample/lib/main.dart
  sample/test/widget_test.dart
  test/consent_mapping_test.dart
  test/smile_id_test.dart
  test/smile_id_test.mocks.dart
Labels: Review effort 3/5

#185 Release 11.0.3
  pubspec.yaml
Labels: Review effort 1/5
